<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-03-06 04:47
=======
# Generated by Django 5.1.6 on 2025-03-03 08:35
>>>>>>> 61501395a45d0896ed30937ad013d8b1af95e297

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
