# Generated by Django 5.1.6 on 2025-02-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_articleimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimages',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
