# Generated by Django 5.1.6 on 2025-03-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_alter_customuser_email'),
        ('newsapp', '0003_article_views_alter_customuser_email'),
    ]

    operations = [
    ]
