# Generated by Django 5.1.6 on 2025-02-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
