# Generated by Django 5.1.6 on 2025-03-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_customuser_profile_pic'),
        ('newsapp', '0004_merge_20250306_1415'),
    ]

    operations = [
    ]
