# Generated by Django 5.1.6 on 2025-04-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='breaking_news',
            field=models.BooleanField(default=False),
        ),
    ]
