# Generated by Django 5.1.6 on 2025-04-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_article_breaking_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='toxicity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
