# Generated by Django 5.1.6 on 2025-04-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_new_inappropriate',
            field=models.BooleanField(default=False),
        ),
    ]
