# Generated by Django 5.1.6 on 2025-04-21 08:35

from django.db import migrations


from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('newsapp', '0010_comment_is_new_inappropriate'),  # Replace with your actual last migration
        ('socialaccount', '0006_alter_socialaccount_extra_data'),  # This is likely the current socialaccount migration
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS socialaccount_socialapp_sites (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                socialapp_id INTEGER NOT NULL REFERENCES socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED,
                site_id INTEGER NOT NULL REFERENCES django_site(id) DEFERRABLE INITIALLY DEFERRED,
                UNIQUE (socialapp_id, site_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS socialaccount_socialapp_sites;"
        ),
    ]
