# Generated by Django 5.1.6 on 2025-04-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_comment_is_new_inappropriate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
