# Generated by Django 5.1.6 on 2025-04-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_create_missing_socialapp_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
