# Generated by Django 5.1.6 on 2025-04-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_alter_customuser_phone'),
        ('newsapp', '0012_alter_customuser_phone'),
    ]

    operations = [
    ]
